XH_repStrs = {"Hated", "Hostile", "Unfriendly", "Neutral", "Friendly", "Honored", "Revered", "Exalted"}

XH_instanceBosses = {
--	["Ragefire Chasm"]={"Oggleflint","Taragaman the Hungerer","Jergosh the Invoker","Bazzalan"},
	["Wailing Caverns"]={"Lady Anacondra","Lord Cobrahn","Lord Pythas","Lord Serpentis","Verdan the Everliving",
		"Mutanus the Devourer","Skum"},
	["Shadowfang Keep"]={"Baron Ashbury","Baron Silverlaine","Commander Springvale","Lord Walden","Lord Godfrey"},
	["Blackfathom Deeps"]={"Ghamoo-Ra","Twilight Lord Kelris","Aku'mai","Lady Sarevess","Gelihast"},
	["Razorfen Kraul"]={"Charlga Razorflank","Overlord Ramtusk","Agathelos the Raging",
		"Death Speaker Jargba","Aggem Thorncurse"},
	--["Gnomeregan"]={"Viscous Fallout","Grubbis","Chomper","Electrocutioner 6000","Crowd Pummeler 9-60",
	--	"Dark Iron Ambassador","Mekgineer Thermaplugg"},
	["Gnomeregan"]={"Viscous Fallout","Electrocutioner 6000","Mekgineer Thermaplugg"},	
--	["Scarlet Monastery"]={"High Inquisitor Fairbanks","Scarlet Commander Mograine","High Inquisitor Whitemane"},
	["Razorfen Downs"]={"Amnennar the Coldbringer","Glutton","Mordresh Fire Eye","Tuten'kash"},
	["Uldaman"]={"Archaedas","Ironaya","Grimlok","Galgann Firehammer","Revelosh"},
	["Zul'Farrak"]={"Chief Ukorz Sandscalp","Ruuzlu","Nekrum Gutchewer","Shadowpriest Sezz'ziz","Sandfury Executioner",
		"Antu'sul","Witch Doctor Zum'rah","Sergeant Bly","Gahz'rilla"},
-- Original
--	["Blackrock Depths"]={"High Interrogator Gerstahn","Bael'Gar","Lord Roccor","Houndmaster Grebmar","Pyromancer Loregrain",
--		"Lord Incendius","Warder Stilgiss","Fineous Darkvire","General Angerforge","Golem Lord Argelmach","Hurley Blackbreath",
--		"Ribbly Screwspigot","Plugger Spazzring","Ambassador Flamelash",
--		"Doom'rel","Magmus","Emperor Dagran Thaurissan","Princess Moira Bronzebeard"},
-- bah
	["Blackrock Depths"]={"Ambassador Flamelash","Doom'rel","Magmus","Emperor Dagran Thaurissan","Princess Moira Bronzebeard"},

	["Dire Maul:East"]={},
	--["Lower Blackrock Spire"]={},
	["Hall of Blackhand"]={"Pyroguard Emberseer","Solakar Flamewreath","Goraluk Anvilcrack","Rend Blackhand","Gyth Blackhand",
		"The Beast","General Drakkisath"},
	["Dire Maul:West"]={},
	["Dire Maul:North"]={},
--	["Stratholme"]={"Stratholme Courier","The Unforgiven","Timmy the Cruel","Archivist Galford","Malor the Zealous",
--		"Cannon Master Willey","Balnazzar","Grand Crusader Dathrohan","Baron Rivendare"},
	["Stratholme"]={"Lord Aurius Rivendare","Ramstein the Gorger","Magistrate Barthilas","Maleki the Pallid","Nerub'enkan","Baroness Anastari"},
	["Scholomance"]={"Blood Steward of Kirtonos","Doctor Theolen Krastinov","Instructor Malicia","Jandice Barov",
		"Lady Illucia Barov","Lord Alexei Barov","Lorekeeper Polkelt","Marduk Blackpool","Ras Frostwhisper","Rattlegore",
		"The Ravenian","Vectus","Darkmaster Gandling"},
-- Death Knight Darkreaver (requires Divination Scryer to summon)
-- Kirtonos the Herald (requires Blood of Innocents to summon)
-- Kormok (requires Brazier of Beckoning or Brazier of Invocation to summon)
-- Lord Blackwood (during of the Scourge Invasion in patch 1.11)

-- Raids
	["Upper Blackrock Spire"]={},
	["Zul'Gurub"]={},
	["Molten Core"]={},
	["Blackwing Lair"]={},
	["Ruins of Ahn'Qiraj"]={},
	["Temple of Ahn'Qiraj"]={},
-- BC
	["Hellfire Citadel: Ramparts"]={"Watchkeeper Gargolmar","Nazan","Omor the Unscarred","Vazruden"},
	["Hellfire Citadel: Ramparts - Heroic"]={"Watchkeeper Gargolmar","Nazan","Omor the Unscarred","Vazruden"},
	["Hellfire Citadel: The Blood Furnace"]={"The Maker","Broggok","Keli'dan the Breaker"},
	["Hellfire Citadel: The Blood Furnace - Heroic"]={"The Maker","Broggok","Keli'dan the Breaker"},
	["Hellfire Citadel: The Shattered Halls"]={"Grand Warlock Nethekurse", "Warbringer O'mrogg", "Warchief Kargath Bladefist"},
	["Hellfire Citadel: The Shattered Halls - Heroic"]={"Grand Warlock Nethekurse", "Warbringer O'mrogg", "Warchief Kargath Bladefist", "Blood Guard Porung"},
	["Coilfang: The Slave Pens"]={"Mennu the Betrayer","Quagmirran","Rokmar the Crackler"},
	["Coilfang: The Slave Pens - Heroic"]={"Mennu the Betrayer","Quagmirran","Rokmar the Crackler"},
	["Coilfang: The Underbog"]={"Ghaz'an","Hungarfen","Swamplord Musel'ek","The Black Stalker"},
	["Coilfang: The Underbog - Heroic"]={"Ghaz'an","Hungarfen","Swamplord Musel'ek","The Black Stalker"},
	["Coilfang: The Steamvault"]={"Hydromancer Thespia","Mekgineer Steamrigger","Warlord Kalithresh"},
	["Coilfang: The Steamvault - Heroic"]={"Hydromancer Thespia","Mekgineer Steamrigger","Warlord Kalithresh"},
	["Auchindoun: Mana-Tombs"]={"Pandemonius","Tavarok","Nexus-Prince Shaffar"},
	["Auchindoun: Mana-Tombs - Heroic"]={"Pandemonius","Tavarok","Nexus-Prince Shaffar"},
	["Auchindoun: Auchenai Crypts"]={"Shirrak the Dead Watcher","Exarch Maladaar"},
	["Auchindoun: Auchenai Crypts - Heroic"]={"Shirrak the Dead Watcher","Exarch Maladaar"},
	["Auchindoun: Sethekk Halls"]={"Darkweaver Syth","Talon King Ikiss"},
	["Auchindoun: Sethekk Halls - Heroic"]={"Darkweaver Syth","Talon King Ikiss","Anzu"},
	["Auchindoun: Shadow Labyrinth"]={"Ambassador Hellmaw","Blackheart the Inciter","Grandmaster Vorpil","Murmur"},
	["Auchindoun: Shadow Labyrinth - Heroic"]={"Ambassador Hellmaw","Blackheart the Inciter","Grandmaster Vorpil","Murmur"},
	["Old Hillsbrad Foothills"]={"Captain Skarloc","Lieutenant Drake","Epoch Hunter"},
	["Old Hillsbrad Foothills - Heroic"]={"Captain Skarloc","Lieutenant Drake","Epoch Hunter"},
	["The Escape From Durnholde"]={"Lieutenant Drake", "Captain Skarloc", "Epoch Hunter"},
	["The Escape From Durnholde - Heroic"]={"Lieutenant Drake", "Captain Skarloc", "Epoch Hunter"},
	["The Black Morass"]={"Chrono Lord Deja", "Temporus", "Aeonus"},
	["The Black Morass - Heroic"]={"Chrono Lord Deja", "Temporus", "Aeonus"},
	["The Mechanar"]={},
	["The Botanica"]={},
	["The Arcatraz"]={},
	["Magister's Terrace"]={"Selin Fireheart","Vexallus","Priestess Delrissa","Kael'thas Sunstrider"},

-- Raids
	["Karazhan"]={},
	["Gruul's Lair"]={"High King Maulgar","Gruul the Dragonkiller"},
	["Magtheridon's Lair"]={},
	["Zul'Aman"]={},
	["Serpentshrine Cavern"]={},
	["Battle for Mount Hyjal"] = {},
	["Black Temple"] = {},
	["Sunwell Plateau"]={"Kalecgos","Sathrovarr the Corruptor","Brutallus","Felmyst","Lady Sacrolash","Grand Warlock Alythess",
			"M'uru","Entropius","Kil'jaeden"},
-- WotLK
	["Utgarde Keep"]={"Prince Keleseth","Dalronn the Controller","Skarvald the Constructor","Ingvar the Plunderer"},
	["Utgarde Keep - Heroic"]={"Prince Keleseth","Dalronn the Controller","Skarvald the Constructor","Ingvar the Plunderer"},
	["The Nexus"]={"Grand Magus Telestra","Ormorok the Tree-Shaper","Anomalus","Keristrasza"},
	["The Nexus - Heroic"]={"Grand Magus Telestra","Ormorok the Tree-Shaper","Anomalus","Keristrasza"},
	["Azjol-Nerub"]={"Krik'thir the Gatewatcher","Hadronox","Anub'arak"},
	["Azjol-Nerub - Heroic"]={"Krik'thir the Gatewatcher","Hadronox","Anub'arak"},
	["Ahn'kahet: The Old Kingdom"]={"Prince Taldaram","Elder Nadox","Jedoga Shadowseeker","Herald Volazj"},
	["Ahn'kahet: The Old Kingdom - Heroic"]={"Prince Taldaram","Elder Nadox","Jedoga Shadowseeker","Herald Volazj","Amanitar"},
	["Drak'Tharon Keep"]={"Trollgore","King Dred","Novos the Summoner","The Prophet Tharon'ja"},
	["Drak'Tharon Keep - Heroic"]={"Trollgore","King Dred","Novos the Summoner","The Prophet Tharon'ja"},
	["Violet Hold"]={"Cyanigosa"},
	["Violet Hold - Heroic"]={"Cyanigosa"},
	["Gundrak"]={"Slad'ran","Drakkari Colossus","Moorabi","Gal'darah"},
	["Gundrak - Heroic"]={"Slad'ran","Drakkari Colossus","Moorabi","Gal'darah","Eck the Ferocious"},
	["Halls of Stone"]={"Maiden of Grief","Krystallus","Sjonnir The Ironshaper"},
	["Halls of Stone - Heroic"]={"Maiden of Grief","Krystallus","Sjonnir The Ironshaper"},
	["Halls of Lightning"]={"General Bjarngrim","Ionar","Volkhan","Loken"},
	["Halls of Lightning - Heroic"]={"General Bjarngrim","Ionar","Volkhan","Loken"},
	["The Oculus"]={"Drakos the Interrogator","Mage-Lord Urom","Varos Cloudstrider","Ley-Guardian Eregos"},
	["The Oculus - Heroic"]={"Drakos the Interrogator","Mage-Lord Urom","Varos Cloudstrider","Ley-Guardian Eregos"},
	["Utgarde Pinnacle"]={"Skadi the Ruthless","King Ymiron","Svala Sorrowgrave","Gortok Palehoof"},
	["Utgarde Pinnacle - Heroic"]={"Skadi the Ruthless","King Ymiron","Svala Sorrowgrave","Gortok Palehoof"},
	["The Culling of Stratholme"]={"Meathook","Chrono-Lord Epoch","Salramm the Fleshcrafter","Infinite Corruptor"},  --"Mal'Ganis"},
	["The Culling of Stratholme - Heroic"]={"Meathook","Chrono-Lord Epoch","Salramm the Fleshcrafter","Infinite Corruptor"},  --"Mal'Ganis"},
	["Trial of the Champion"]={"The Black Knight"},
	["Trial of the Champion - Heroic"]={"The Black Knight"},
-- Raids
	["Naxxramas"]={"Anub'Rekhan","Grand Widow Faerlina","Maexxna",    -- Arachnid Quarter
		"Noth the Plaguebringer","Heigan the Unclean","Loatheb",    -- Plague Quarter
		"Instructor Razuvious","Gothik the Harvester","Thane Korth'azz","Baron Rivendare","Lady Blaumeux","Sir Zeliek",    -- Military
		"Patchwerk","Grobbulus","Gluth","Thaddius",    -- Construct Quarter
		"Sapphiron","Kel'Thuzad"},
	["The Eye of Eternity"]={"Malygos",},
	["Ulduar"]={"Flame Leviathan","Ignis the Furnace Master","Razorscale","XT-002 Deconstructor",
		"Assembly of Iron","Kologarn","Auriaya",
		"Mimiron","Freya","Thorim","Hodir",
		"General Vezax","Yogg-Saron","Algalon the Observer"},
	["Trial of the Crusader"]={"Gormok the Impaler","Acidmaw","Dreadscale","Icehowl","Lord Jaraxxus","Edyis Darkbane",
		"Fjola Lightbane","Anub'arak"},
	["The Obsidian Sanctum"] = {"Sartharion"},
-- Patch 3.3
	["The Forge of Souls"]={"Bronjahm","Devourer of Souls"},
	["The Forge of Souls - Heroic"]={"Bronjahm","Devourer of Souls"},
	["Halls of Reflection"]={"Falric","Marwyn"},   --"the Lich King"},  -- Not killed here
	["Halls of Reflection - Heroic"]={"Falric","Marwyn"},   --"the Lich King"},  -- Not killed here
	["Pit of Saron"]={"Forgemaster Garfrost","Ick","Krick","Scourgelord Tyrannus"},
	["Pit of Saron - Heroic"]={"Forgemaster Garfrost","Ick","Krick","Scourgelord Tyrannus"},
-- Raids
	["Icecrown Citadel"]={"Lord Marrowgar","Lady Deathwhisper","Deathbringer Saurfang","Blood Prince Council",
		"Blood-Queen Lana'thel","Festergut","Rotface","Professor Putricide","Valithiria Dreamwalker",
		"Sindragosa","The Lich King"},
-- Cata
-- Old World redone:
	["Stormwind Stockade"]={"Randolph Moloch","Lord Overheat","Hogger"},
	["Deadmines"]={"Glubtok","Helix Gearbreaker","Foe Reaper 5000","Admiral Ripsnarl","\"Captain\" Cookie"},
	["Deadmines - Heroic"]={"Glubtok","Helix Gearbreaker","Foe Reaper 5000","Admiral Ripsnarl","\"Captain\" Cookie","Vanessa VanCleef"},
	["Sunken Temple"]={"Dreamscythe","Weaver","Hazzas","Morphaz","Shade of Eranikus","Ogom the Wretched",
			"Jammal'an the Prophet","Avatar of Hakkar"},
	["Shadowfang Keep"]={"Baron Ashbury","Baron Silverlaine","Commander Springvale","Lord Walden","Lord Godfrey"},
	["Shadowfang Keep - Heroic"]={"Baron Ashbury","Baron Silverlaine","Commander Springvale","Lord Walden","Lord Godfrey"},
-- New
	--["Throne of the Tides"]={"Lady Naz'jar","Commander Ulthok","Erunak Stonespeaker","Ozumat"},
	["Throne of the Tides"]={"Lady Naz'jar","Commander Ulthok","Mindbender Ghur'sha","Ozumat"},
	["Throne of the Tides - Heroic"]={"Lady Naz'jar","Commander Ulthok","Mindbender Ghur'sha","Ozumat"},
	["Blackrock Caverns"]={"Rom'ogg Bonecrusher","Corla, Herald of Twilight","Karsh Steelbender","Beauty","Ascendant Lord Obsidius"},
	["Blackrock Caverns - Heroic"]={"Rom'ogg Bonecrusher","Corla, Herald of Twilight","Karsh Steelbender","Beauty","Ascendant Lord Obsidius"},
	["Blackwing Descent"]={"Magmaw",
			"Arcanotron","Electron","Magmatron","Toxitron",
			"Maloriak",
			"Atramedes",
			"Chimaeron",
			"Nefarian"},
	["The Stonecore"]={"Corborus","Slabhide","Ozruk","High Priestess Azil"},
	["The Stonecore - Heroic"]={"Corborus","Slabhide","Ozruk","High Priestess Azil"},
	["The Vortex Pinnacle"]={"Grand Vizier Ertan","Altairus","Asaad"},
	["The Vortex Pinnacle - Heroic"]={"Grand Vizier Ertan","Altairus","Asaad"},
	["Halls of Origination"]={"Isiset","Rajh","Ammunae","Setesh","Anraphet","Earthrager Ptah","Temple Guardian Anhuur",},
	["Halls of Origination - Heroic"]={"Isiset","Rajh","Ammunae","Setesh","Anraphet","Earthrager Ptah","Temple Guardian Anhuur",},
	["Grim Batol"]={"Drahga Shadowburner","Forgemaster Throngus","Erudax","General Umbriss",},
	["Grim Batol - Heroic"]={"Drahga Shadowburner","Forgemaster Throngus","Erudax","General Umbriss",},
	["Lost City of the Tol'vir"]={"General Husam","High Prophet Barim","Lockmaw","Siamat",},
	["Lost City of the Tol'vir - Heroic"]={"General Husam","High Prophet Barim","Lockmaw","Augh","Siamat",},
-- Patch 4.3.0
	["End Time"]={"Murozond"},
	["End Time - Herioc"]={"Murozond"},
	["Well of Eternity"]={"Peroth'arn","Azshara","Mannoroth","Varo'then"},
	["Well of Eternity - Heroic"]={"Peroth'arn","Azshara","Mannoroth","Varo'then"},
	["Hour of Twilight"]={"Arcurion","Asira Dawnslayer","Archbishop Benedictus"},
	["Hour of Twilight - Heroic"]={"Arcurion","Lava Guard Gordoth","Dark Shaman Koranthal"},

-- MoP redos
	["Ragefire Chasm"]={"Slagmaw","Adarogg","Jergosh the Invoker","Bazzalan"},

-- MoP New
	["Stormstout Brewery"]={"Hoptallus","Yan-Zhu the Uncasked","Ook-Ook"},
	["Mogu'shan Palace"]={"Gekkan","Ghost Iron Dragonling","Xin the Weaponmaster","Harthak Flameseeker"},
	["Temple of the Jade Serpent"]={"Haunting Sha","Wise Mari","Liu Flameheart"},

-- MoP Redos
	["Scarlet Halls"]={"Houndmaster Braun","Commander Lindon","Armsmaster Harlan","Sergeant Verdone","Flameweaver Koegler"},
	["Scarlet Monastery"]={"Brother Korloff","High Inquisitor Whitemane","Thalnos the Soulrender"},
}
